version: '2'

services:

  sc-flask:
    restart: always
    command: bash docker/entrypoint.prod.sh
    env_file:
      - server/env/.prod.env
    volumes:
      - ./server/:/opt/sc/sc-flask
      - ./client/:/opt/sc/frontend
    ports:
      - '5001:5000'

  sc-nginx:
    restart: always
    volumes:
      - ./client/:/opt/sc/static
    command: bash entry-point.prod.sh
    environment:
      - NODE_ENV='production'

  sc-arangodb:
    restart: always
    env_file:
      - server/env/.prod.env
    ports:
      - '8529:8529'

  sc-frontend-builder:
    command: bash builder.sh
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend

  sc-swagger:
    restart: always
    ports:
      - '8080:8080'
    environment:
      - "API_URL=https://suttacentral.net/api/swagger.json"

  sc-elasticsearch:
    restart: always
    ports:
    - '9200:9200'
    - '9300:9300'
    
  sc-chrome-headless:
    restart: always
    ports:
     - '9222:9222'
